//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Estudio.Controllers.prueba {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceOficialesSoap", Namespace="http://eisei.net.mx/webserviceoficiales")]
    public partial class WebServiceOficiales : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback calculoXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback calculoMejorasOperationCompleted;
        
        private System.Threading.SendOrPostCallback grabarExcepcionExternaOperationCompleted;
        
        private System.Threading.SendOrPostCallback guardarMejorasOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceOficiales() {
            this.Url = global::Estudio.Controllers.Properties.Settings.Default.Estudio_Controllers_prueba_WebServiceOficiales;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event calculoXMLCompletedEventHandler calculoXMLCompleted;
        
        /// <remarks/>
        public event calculoMejorasCompletedEventHandler calculoMejorasCompleted;
        
        /// <remarks/>
        public event grabarExcepcionExternaCompletedEventHandler grabarExcepcionExternaCompleted;
        
        /// <remarks/>
        public event guardarMejorasCompletedEventHandler guardarMejorasCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eisei.net.mx/webserviceoficiales/calculoXML", RequestNamespace="http://eisei.net.mx/webserviceoficiales", ResponseNamespace="http://eisei.net.mx/webserviceoficiales", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string calculoXML(string @__docXML, string nombreArchivo, string usuario) {
            object[] results = this.Invoke("calculoXML", new object[] {
                        @__docXML,
                        nombreArchivo,
                        usuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void calculoXMLAsync(string @__docXML, string nombreArchivo, string usuario) {
            this.calculoXMLAsync(@__docXML, nombreArchivo, usuario, null);
        }
        
        /// <remarks/>
        public void calculoXMLAsync(string @__docXML, string nombreArchivo, string usuario, object userState) {
            if ((this.calculoXMLOperationCompleted == null)) {
                this.calculoXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalculoXMLOperationCompleted);
            }
            this.InvokeAsync("calculoXML", new object[] {
                        @__docXML,
                        nombreArchivo,
                        usuario}, this.calculoXMLOperationCompleted, userState);
        }
        
        private void OncalculoXMLOperationCompleted(object arg) {
            if ((this.calculoXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculoXMLCompleted(this, new calculoXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eisei.net.mx/webserviceoficiales/calculoMejoras", RequestNamespace="http://eisei.net.mx/webserviceoficiales", ResponseNamespace="http://eisei.net.mx/webserviceoficiales", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object calculoMejoras(string cuspp, int num_oper, string modalidad, string moneda, int aniosRT, double porcentajeRVD, int periodoGarantizado, string derechoCrecer, string gratificacion, bool prc_Tv, double prc_Com) {
            object[] results = this.Invoke("calculoMejoras", new object[] {
                        cuspp,
                        num_oper,
                        modalidad,
                        moneda,
                        aniosRT,
                        porcentajeRVD,
                        periodoGarantizado,
                        derechoCrecer,
                        gratificacion,
                        prc_Tv,
                        prc_Com});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void calculoMejorasAsync(string cuspp, int num_oper, string modalidad, string moneda, int aniosRT, double porcentajeRVD, int periodoGarantizado, string derechoCrecer, string gratificacion, bool prc_Tv, double prc_Com) {
            this.calculoMejorasAsync(cuspp, num_oper, modalidad, moneda, aniosRT, porcentajeRVD, periodoGarantizado, derechoCrecer, gratificacion, prc_Tv, prc_Com, null);
        }
        
        /// <remarks/>
        public void calculoMejorasAsync(string cuspp, int num_oper, string modalidad, string moneda, int aniosRT, double porcentajeRVD, int periodoGarantizado, string derechoCrecer, string gratificacion, bool prc_Tv, double prc_Com, object userState) {
            if ((this.calculoMejorasOperationCompleted == null)) {
                this.calculoMejorasOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalculoMejorasOperationCompleted);
            }
            this.InvokeAsync("calculoMejoras", new object[] {
                        cuspp,
                        num_oper,
                        modalidad,
                        moneda,
                        aniosRT,
                        porcentajeRVD,
                        periodoGarantizado,
                        derechoCrecer,
                        gratificacion,
                        prc_Tv,
                        prc_Com}, this.calculoMejorasOperationCompleted, userState);
        }
        
        private void OncalculoMejorasOperationCompleted(object arg) {
            if ((this.calculoMejorasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculoMejorasCompleted(this, new calculoMejorasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eisei.net.mx/webserviceoficiales/grabarExcepcionExterna", RequestNamespace="http://eisei.net.mx/webserviceoficiales", ResponseNamespace="http://eisei.net.mx/webserviceoficiales", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string grabarExcepcionExterna(string cuspp, int num_operacion, string modalidad, string moneda, int aniosRT, double porcentajeRVD, int periodoGarantizado, string derechoCrecer, string gratificacion) {
            object[] results = this.Invoke("grabarExcepcionExterna", new object[] {
                        cuspp,
                        num_operacion,
                        modalidad,
                        moneda,
                        aniosRT,
                        porcentajeRVD,
                        periodoGarantizado,
                        derechoCrecer,
                        gratificacion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void grabarExcepcionExternaAsync(string cuspp, int num_operacion, string modalidad, string moneda, int aniosRT, double porcentajeRVD, int periodoGarantizado, string derechoCrecer, string gratificacion) {
            this.grabarExcepcionExternaAsync(cuspp, num_operacion, modalidad, moneda, aniosRT, porcentajeRVD, periodoGarantizado, derechoCrecer, gratificacion, null);
        }
        
        /// <remarks/>
        public void grabarExcepcionExternaAsync(string cuspp, int num_operacion, string modalidad, string moneda, int aniosRT, double porcentajeRVD, int periodoGarantizado, string derechoCrecer, string gratificacion, object userState) {
            if ((this.grabarExcepcionExternaOperationCompleted == null)) {
                this.grabarExcepcionExternaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngrabarExcepcionExternaOperationCompleted);
            }
            this.InvokeAsync("grabarExcepcionExterna", new object[] {
                        cuspp,
                        num_operacion,
                        modalidad,
                        moneda,
                        aniosRT,
                        porcentajeRVD,
                        periodoGarantizado,
                        derechoCrecer,
                        gratificacion}, this.grabarExcepcionExternaOperationCompleted, userState);
        }
        
        private void OngrabarExcepcionExternaOperationCompleted(object arg) {
            if ((this.grabarExcepcionExternaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.grabarExcepcionExternaCompleted(this, new grabarExcepcionExternaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://eisei.net.mx/webserviceoficiales/guardarMejoras", RequestNamespace="http://eisei.net.mx/webserviceoficiales", ResponseNamespace="http://eisei.net.mx/webserviceoficiales", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public object guardarMejoras(string cuspp, int num_oper, string modalidad, string moneda, int aniosRT, double porcentajeRVD, int periodoGarantizado, string derechoCrecer, string gratificacion, bool prc_Tv, double prc_Com) {
            object[] results = this.Invoke("guardarMejoras", new object[] {
                        cuspp,
                        num_oper,
                        modalidad,
                        moneda,
                        aniosRT,
                        porcentajeRVD,
                        periodoGarantizado,
                        derechoCrecer,
                        gratificacion,
                        prc_Tv,
                        prc_Com});
            return ((object)(results[0]));
        }
        
        /// <remarks/>
        public void guardarMejorasAsync(string cuspp, int num_oper, string modalidad, string moneda, int aniosRT, double porcentajeRVD, int periodoGarantizado, string derechoCrecer, string gratificacion, bool prc_Tv, double prc_Com) {
            this.guardarMejorasAsync(cuspp, num_oper, modalidad, moneda, aniosRT, porcentajeRVD, periodoGarantizado, derechoCrecer, gratificacion, prc_Tv, prc_Com, null);
        }
        
        /// <remarks/>
        public void guardarMejorasAsync(string cuspp, int num_oper, string modalidad, string moneda, int aniosRT, double porcentajeRVD, int periodoGarantizado, string derechoCrecer, string gratificacion, bool prc_Tv, double prc_Com, object userState) {
            if ((this.guardarMejorasOperationCompleted == null)) {
                this.guardarMejorasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnguardarMejorasOperationCompleted);
            }
            this.InvokeAsync("guardarMejoras", new object[] {
                        cuspp,
                        num_oper,
                        modalidad,
                        moneda,
                        aniosRT,
                        porcentajeRVD,
                        periodoGarantizado,
                        derechoCrecer,
                        gratificacion,
                        prc_Tv,
                        prc_Com}, this.guardarMejorasOperationCompleted, userState);
        }
        
        private void OnguardarMejorasOperationCompleted(object arg) {
            if ((this.guardarMejorasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.guardarMejorasCompleted(this, new guardarMejorasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void calculoXMLCompletedEventHandler(object sender, calculoXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculoXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculoXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void calculoMejorasCompletedEventHandler(object sender, calculoMejorasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculoMejorasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculoMejorasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void grabarExcepcionExternaCompletedEventHandler(object sender, grabarExcepcionExternaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class grabarExcepcionExternaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal grabarExcepcionExternaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void guardarMejorasCompletedEventHandler(object sender, guardarMejorasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class guardarMejorasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal guardarMejorasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591