//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estudio.Controllers.wsXML {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsXML.WebServiceXMLSoap")]
    public interface WebServiceXMLSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento docXML del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/guardarXML", ReplyAction="*")]
        Estudio.Controllers.wsXML.guardarXMLResponse guardarXML(Estudio.Controllers.wsXML.guardarXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/guardarXML", ReplyAction="*")]
        System.Threading.Tasks.Task<Estudio.Controllers.wsXML.guardarXMLResponse> guardarXMLAsync(Estudio.Controllers.wsXML.guardarXMLRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento numArch del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerXML", ReplyAction="*")]
        Estudio.Controllers.wsXML.obtenerXMLResponse obtenerXML(Estudio.Controllers.wsXML.obtenerXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerXML", ReplyAction="*")]
        System.Threading.Tasks.Task<Estudio.Controllers.wsXML.obtenerXMLResponse> obtenerXMLAsync(Estudio.Controllers.wsXML.obtenerXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class guardarXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="guardarXML", Namespace="http://tempuri.org/", Order=0)]
        public Estudio.Controllers.wsXML.guardarXMLRequestBody Body;
        
        public guardarXMLRequest() {
        }
        
        public guardarXMLRequest(Estudio.Controllers.wsXML.guardarXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class guardarXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string docXML;
        
        public guardarXMLRequestBody() {
        }
        
        public guardarXMLRequestBody(string docXML) {
            this.docXML = docXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class guardarXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="guardarXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public Estudio.Controllers.wsXML.guardarXMLResponseBody Body;
        
        public guardarXMLResponse() {
        }
        
        public guardarXMLResponse(Estudio.Controllers.wsXML.guardarXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class guardarXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string guardarXMLResult;
        
        public guardarXMLResponseBody() {
        }
        
        public guardarXMLResponseBody(string guardarXMLResult) {
            this.guardarXMLResult = guardarXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerXML", Namespace="http://tempuri.org/", Order=0)]
        public Estudio.Controllers.wsXML.obtenerXMLRequestBody Body;
        
        public obtenerXMLRequest() {
        }
        
        public obtenerXMLRequest(Estudio.Controllers.wsXML.obtenerXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numArch;
        
        public obtenerXMLRequestBody() {
        }
        
        public obtenerXMLRequestBody(string numArch) {
            this.numArch = numArch;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public Estudio.Controllers.wsXML.obtenerXMLResponseBody Body;
        
        public obtenerXMLResponse() {
        }
        
        public obtenerXMLResponse(Estudio.Controllers.wsXML.obtenerXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerXMLResult;
        
        public obtenerXMLResponseBody() {
        }
        
        public obtenerXMLResponseBody(string obtenerXMLResult) {
            this.obtenerXMLResult = obtenerXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceXMLSoapChannel : Estudio.Controllers.wsXML.WebServiceXMLSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceXMLSoapClient : System.ServiceModel.ClientBase<Estudio.Controllers.wsXML.WebServiceXMLSoap>, Estudio.Controllers.wsXML.WebServiceXMLSoap {
        
        public WebServiceXMLSoapClient() {
        }
        
        public WebServiceXMLSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceXMLSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceXMLSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceXMLSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Estudio.Controllers.wsXML.guardarXMLResponse Estudio.Controllers.wsXML.WebServiceXMLSoap.guardarXML(Estudio.Controllers.wsXML.guardarXMLRequest request) {
            return base.Channel.guardarXML(request);
        }
        
        public string guardarXML(string docXML) {
            Estudio.Controllers.wsXML.guardarXMLRequest inValue = new Estudio.Controllers.wsXML.guardarXMLRequest();
            inValue.Body = new Estudio.Controllers.wsXML.guardarXMLRequestBody();
            inValue.Body.docXML = docXML;
            Estudio.Controllers.wsXML.guardarXMLResponse retVal = ((Estudio.Controllers.wsXML.WebServiceXMLSoap)(this)).guardarXML(inValue);
            return retVal.Body.guardarXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Estudio.Controllers.wsXML.guardarXMLResponse> Estudio.Controllers.wsXML.WebServiceXMLSoap.guardarXMLAsync(Estudio.Controllers.wsXML.guardarXMLRequest request) {
            return base.Channel.guardarXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Estudio.Controllers.wsXML.guardarXMLResponse> guardarXMLAsync(string docXML) {
            Estudio.Controllers.wsXML.guardarXMLRequest inValue = new Estudio.Controllers.wsXML.guardarXMLRequest();
            inValue.Body = new Estudio.Controllers.wsXML.guardarXMLRequestBody();
            inValue.Body.docXML = docXML;
            return ((Estudio.Controllers.wsXML.WebServiceXMLSoap)(this)).guardarXMLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Estudio.Controllers.wsXML.obtenerXMLResponse Estudio.Controllers.wsXML.WebServiceXMLSoap.obtenerXML(Estudio.Controllers.wsXML.obtenerXMLRequest request) {
            return base.Channel.obtenerXML(request);
        }
        
        public string obtenerXML(string numArch) {
            Estudio.Controllers.wsXML.obtenerXMLRequest inValue = new Estudio.Controllers.wsXML.obtenerXMLRequest();
            inValue.Body = new Estudio.Controllers.wsXML.obtenerXMLRequestBody();
            inValue.Body.numArch = numArch;
            Estudio.Controllers.wsXML.obtenerXMLResponse retVal = ((Estudio.Controllers.wsXML.WebServiceXMLSoap)(this)).obtenerXML(inValue);
            return retVal.Body.obtenerXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Estudio.Controllers.wsXML.obtenerXMLResponse> Estudio.Controllers.wsXML.WebServiceXMLSoap.obtenerXMLAsync(Estudio.Controllers.wsXML.obtenerXMLRequest request) {
            return base.Channel.obtenerXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<Estudio.Controllers.wsXML.obtenerXMLResponse> obtenerXMLAsync(string numArch) {
            Estudio.Controllers.wsXML.obtenerXMLRequest inValue = new Estudio.Controllers.wsXML.obtenerXMLRequest();
            inValue.Body = new Estudio.Controllers.wsXML.obtenerXMLRequestBody();
            inValue.Body.numArch = numArch;
            return ((Estudio.Controllers.wsXML.WebServiceXMLSoap)(this)).obtenerXMLAsync(inValue);
        }
    }
}
