//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Estudio.WebService.webPrueba {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AdmIntegracionCotizadorSoap", Namespace="http://tempuri.org/")]
    public partial class AdmIntegracionCotizador : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CargarCotizacionesOficialesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ActualizarProductoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AdmIntegracionCotizador() {
            this.Url = global::Estudio.WebService.Properties.Settings.Default.Estudio_WebService_webPrueba_AdmIntegracionCotizador;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CargarCotizacionesOficialesCompletedEventHandler CargarCotizacionesOficialesCompleted;
        
        /// <remarks/>
        public event ActualizarProductoCompletedEventHandler ActualizarProductoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CargarCotizacionesOficiales", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CargarCotizacionesOficiales(string contenidoArchivoXML, string nombreArchivoXML) {
            object[] results = this.Invoke("CargarCotizacionesOficiales", new object[] {
                        contenidoArchivoXML,
                        nombreArchivoXML});
            return ((string)(results[0]));
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/calculoMejoras", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CalculoMejoras(object contenidoArchivoXML/*, string nombreArchivoXML*/)
        {
            object[] results = this.Invoke("CalculoMejoras", new object[] {
                        contenidoArchivoXML
                        /*nombreArchivoXML*/});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CargarCotizacionesOficialesAsync(string contenidoArchivoXML, string nombreArchivoXML) {
            this.CargarCotizacionesOficialesAsync(contenidoArchivoXML, nombreArchivoXML, null);
        }
        
        /// <remarks/>
        public void CargarCotizacionesOficialesAsync(string contenidoArchivoXML, string nombreArchivoXML, object userState) {
            if ((this.CargarCotizacionesOficialesOperationCompleted == null)) {
                this.CargarCotizacionesOficialesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCargarCotizacionesOficialesOperationCompleted);
            }
            this.InvokeAsync("CargarCotizacionesOficiales", new object[] {
                        contenidoArchivoXML,
                        nombreArchivoXML}, this.CargarCotizacionesOficialesOperationCompleted, userState);
        }
        
        private void OnCargarCotizacionesOficialesOperationCompleted(object arg) {
            if ((this.CargarCotizacionesOficialesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CargarCotizacionesOficialesCompleted(this, new CargarCotizacionesOficialesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ActualizarProducto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ActualizarProducto(string nroOperacion, string jsonValores) {
            object[] results = this.Invoke("ActualizarProducto", new object[] {
                        nroOperacion,
                        jsonValores});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizarProductoAsync(string nroOperacion, string jsonValores) {
            this.ActualizarProductoAsync(nroOperacion, jsonValores, null);
        }
        
        /// <remarks/>
        public void ActualizarProductoAsync(string nroOperacion, string jsonValores, object userState) {
            if ((this.ActualizarProductoOperationCompleted == null)) {
                this.ActualizarProductoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizarProductoOperationCompleted);
            }
            this.InvokeAsync("ActualizarProducto", new object[] {
                        nroOperacion,
                        jsonValores}, this.ActualizarProductoOperationCompleted, userState);
        }
        
        private void OnActualizarProductoOperationCompleted(object arg) {
            if ((this.ActualizarProductoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizarProductoCompleted(this, new ActualizarProductoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void CargarCotizacionesOficialesCompletedEventHandler(object sender, CargarCotizacionesOficialesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CargarCotizacionesOficialesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CargarCotizacionesOficialesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void ActualizarProductoCompletedEventHandler(object sender, ActualizarProductoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizarProductoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizarProductoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591